spring:
  application:
    name: message-sender
       
message-sender:
 signature: ${spring.application.name}:${random.value}
 
server:
 port: 0
 
message-printer:
 protocol: http://
 path: messages
 user: user
 pass: password
 ribbon:
  eureka:
   enabled: true
  ServerListRefreshInterval: 5000
ribbon:
 ConnectTimeout: 1000
 ReadTimeout: 1000

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:1099/eureka
  register-with-eureka: false
  registryFetchIntervalSeconds: 2
  
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 2000
  circuitBreaker:
   requestVolumeThreshold: 4
   sleepWindowInMilliseconds: 50000
   errorThresholdPercentage: 50