message-sender:
 signature: ${spring.application.name}:${random.value}
 
server:
 port: 0
 
message-printer:
 protocol: http://
 path: messages
 user: user
 pass: password

ribbon:
 ConnectTimeout: 1000
 ReadTimeout: 1000

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:1099/eureka
  register-with-eureka: true
  registryFetchIntervalSeconds: 2
 instance:
  instanceId: ${spring.application.name}:${random.value}
  healthCheckUrlPath: /actuator/health
  statusPageUrl: /actuator/health
  
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 3000
  circuitBreaker:
   requestVolumeThreshold: 4
   sleepWindowInMilliseconds: 50000
   errorThresholdPercentage: 50