message-printer:
 signature: ${spring.application.name}:${random.value}
 user: user
 pass: password
    
server:
 port: 0
 
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:1099/eureka
 instance:
  instanceId: ${spring.application.name}
  healthCheckUrlPath: /actuator/health
  statusPageUrl: /actuator/health